# docker-compose.yml (Postgres + Node)
services:
  db_sql:
    image: postgres:16
    container_name: app-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
    expose:
      - "5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d app"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - shared-global-network

  api:
    build: ./smsserver
    container_name: smsserver-api
    restart: unless-stopped
    depends_on:
      db_sql:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 4000
      DATABASE_URL: postgres://appuser:apppass@db_sql:5432/app
    ports:
      - "4000:4000"
    networks:
      - shared-global-network
    # remove volumes for production, use only for development
    #volumes:
    #  - ./smsserver:/usr/src/app

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "4001:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin2@test.com
      PGADMIN_DEFAULT_PASSWORD: admin2
      PGADMIN_CONFIG_MAX_LOGIN_ATTEMPTS: 0
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - shared-global-network

volumes:
  db_data:
  pgadmin_data:
  
networks:
  shared-global-network:
    external: true
